# Generated by Django 2.2 on 2019-05-27 19:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190527_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/static/images'), upload_to=''),
        ),
    ]
