# Generated by Django 2.2 on 2019-05-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190527_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
