# Generated by Django 2.2 on 2019-05-27 20:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_auto_20190527_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=60)),
                ('cover', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/static/images'), upload_to='')),
            ],
        ),
    ]
