# Generated by Django 2.2 on 2019-05-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='cover',
        ),
    ]
