# Generated by Django 2.2 on 2019-05-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_projectmodel_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
