# Generated by Django 2.2 on 2019-05-27 20:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/static/images'), upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='images',
            field=models.ManyToManyField(to='projects.ImageModel'),
        ),
    ]
