# Generated by Django 2.2 on 2019-05-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190527_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='images',
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
