# Generated by Django 2.2 on 2019-05-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
