# Generated by Django 2.2 on 2019-05-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190527_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectModel',
        ),
    ]
