# Generated by Django 2.2 on 2019-05-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20190527_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
