# Generated by Django 2.2 on 2019-05-27 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20190527_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectModel',
            new_name='Project',
        ),
    ]
